### ISSUE TITLE
f

### ISSUE THREAD

**Issue by PR4GM4** [alexk111/DeBitpay#1]
The link of "https://www.garyshood.com/bitpay/" that guy just robbed it from me. Look on the reddit page and you will see.

**Comment by alexk111** [comment]
Could you post a link to the original one?

**Comment by PR4GM4** [comment]
https://www.reddit.com/r/Bitcoin/comments/7ntfv6/psa_how_to_get_address_from_bitpay_uri_now/dwhbi0w/

**Comment by ericol** [comment]
@alexk111 duuude. Thanks. I just used the app, and it rocked.

**Comment by alexk111** [comment]
@ericol 🙌

**Comment by yilmzfurkan** [comment]
@alexk111 would it possible the add qr code?

**Comment by alexk111** [comment]
@yilmzfurkan I think so. Please add a separate issue for this.

**Comment by avx007** [comment]
Thank you alexk111  --- your app works 👍👍

**Comment by alexk111** [comment]
@PR4GM4 Just FYI The link was removed from the readme, since the original source is unknown.
