### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by teasider** [alexk111/DeBitpay#15]
Just tried running it for a payment to a file server website (uploaded.net)
and i get an error: "**Could not get data for the specified payment request**"

**Comment by alexk111** [comment]
What step do you get the error at? I've just tried to debitpay a BTC invoice - everything worked ok, it returned the address/amount data.

**Comment by teasider** [comment]
I've copied the payment link and it returns the error when i try to "convert" it.
Tried a couple of times getting the same error

**Comment by alexk111** [comment]
Clicked Pay on uploaded.net, then chose BTC and entered email on the bitpay page, before copying the link, right?

**Comment by teasider** [comment]
Yap, exactly.
then on the bitpay page I chose Copy payment link (like always)
Only this time it wasnt working for me.
Are you not getting the same error? Maybe i should try a different browser?

**Comment by alexk111** [comment]
Can you try to "debitpay" the invoice url in a private browsing window (ctrl/cmd + shift + n) with a VPN turned on (if you have one)?

**Comment by teasider** [comment]
This was actually done with a VPN on.
I'll give it a try.

**Comment by alexk111** [comment]
Tried it for uploaded.net. Worked ok, in a private browsing window with VPN.

**Comment by Petachok13** [comment]
> Это было на самом деле сделано с включенным VPN. 
> Я попробую.

Hello. I'm talking about your forgotten password topic from ETH. Please write me - Amozon@protonmail.com

**Comment by teasider** [comment]
> Tried it for uploaded.net. Worked ok, in a private browsing window with VPN.

Hi, thank you.
Can confirm it works on a private window with VPN on.
(Doesnt work on regular chrome window with VPN on)

**Comment by alexk111** [comment]
Thanks for the confirmation!
It's probably related to some data stored by bitpay or uploaded.net in browser cookies and/or localstorage. Next time you might try to clear cookies and local stored data for bitpay and uploaded.net before making a payment - maybe it will solve the problem for non-private windows.
