### ISSUE TITLE
Library no longer working

### ISSUE THREAD

**Issue by juouy** [alexk111/DeBitpay#16]
Bitpay blocked this method by requiring user interaction on the invoice page. The interaction required is choosing the payment currency BTC/LTC etc.

Server is now returning 400 error.

> < HTTP/2 400
> < content-type: text/html; charset=utf-8
> < content-length: 70
> 
> Currency not yet selected on invoice page, please select and try again
>

**Comment by alexk111** [comment]
That's ok. They always required this. You need to complete the interaction and when they show a countdown timer you can copy/paste the link. Try it again.

**Comment by juouy** [comment]
Not really, due to fact that we had simple implementation that was creating invoice via API then doing curl request to bitpay.com/i/[invoiceid] and it was working flawlessly for months.

It was killed recently ;)

**Comment by alexk111** [comment]
Hm, interesting. Didn't know that they allowed to get the data before filling in the required forms. 

Thanks for the heads-up! It's always helpful to know of any changes on Bitpay side :)
