### ISSUE TITLE
QR Code 

### ISSUE THREAD

**Issue by yilmzfurkan** [alexk111/DeBitpay#3]
The problem with BitPay is because they switched from BIP21 to BIP70 (https://blog.samouraiwallet.com/post/169222582782/bitpay-qr-codes-are-no-longer-valid-important) which isn't a standard. Since "DeBitpay" can successfully extract the data creating a BIP21 QR code would be awesome and easier for many people. Thanks.

**Comment by alexk111** [comment]
Thanks for the idea! Implemented and published. QR Code and BIP 0021 URI (Open in Wallet) go below the amount/address fields. Please check the updated version and close the issue if that's what you asked for :)

**Comment by yilmzfurkan** [comment]
@alexk111 thanks!
