### ISSUE TITLE
I think maybe they patched something because this doesn't work 

### ISSUE THREAD

**Issue by offsecn00b** [alexk111/DeBitpay#7]
Everything installs and compiles fine but it results in communication error when you test a uri.

**Comment by alexk111** [comment]
Just checked it, processed a url without problems.

Please provide a step-by-step instruction on how to reproduce the error. Also check the dev console if there are any error details on the network request.

**Comment by offsecn00b** [comment]
You're right, I can't replicate it today. Maybe there was a temporary API outage or something from them or network issue on my side. Nice tool btw and thanks for the fast reply!
