### ISSUE TITLE
Payment didnt arrive.

### ISSUE THREAD

**Issue by FreeBornAngel** [alexk111/DeBitpay#8]
I used your code but didn't receive payment.
https://explorer.bitcoin.com/bch/address/19Seq8PwtHzFh6aLXYebadeebNuNq7pFaD

I hope you can help.

**Comment by alexk111** [comment]
Thanks for the report. If the payment wasn't confirmed on bitpay side, please contact bitpay support to find out what went wrong.  If the payment was confirmed by bitpay, and wasn't confirmed on the merchant side (final recipient), then ask the merchant to check it.

**Comment by FreeBornAngel** [comment]
Ok, I got bitpay on the line. 

    On Sunday, October 14, 2018 3:16 AM, Alex Kaul <notifications@github.com> wrote:
 

 Thanks for the report. If the payment wasn't confirmed on bitpay side, please contact bitpay support to find out what went wrong. If the payment was confirmed by bitpay, and wasn't confirmed on the merchant side (final recipient), then ask the merchant to check it.—

**Comment by alexk111** [comment]
@FreeBornAngel 👍 Please keep me updated on this.

**Comment by FreeBornAngel** [comment]
Sure will, I would like to get my ten bucks back,...
I'm on a Samsung tab4.Right now the bitcoin.com wallet won't interact with the qr code, nor the link.The wallet says my clipboard is empty, but when I paste the code anyway it does nothing.When I scan the qr code from the desktop it just freezes the wallet.And now bitpay is slow playing me. 

    On Sunday, October 14, 2018 9:14 PM, Alex Kaul <notifications@github.com> wrote:
 

 @FreeBornAngel 👍 Please keep me updated on this.—

**Comment by FreeBornAngel** [comment]
BitPay found that 10usd, I sent bch to a btc address, you might want to clarify that on your site.



Sent from Yahoo Mail on Android 
 
  On Mon, Oct 15, 2018 at 3:39 PM, Angel<thefreebornsociety@yahoo.com> wrote:   Sure will, I would like to get my ten bucks back,...
I'm on a Samsung tab4.Right now the bitcoin.com wallet won't interact with the qr code, nor the link.The wallet says my clipboard is empty, but when I paste the code anyway it does nothing.When I scan the qr code from the desktop it just freezes the wallet.And now bitpay is slow playing me. 

    On Sunday, October 14, 2018 9:14 PM, Alex Kaul <notifications@github.com> wrote:
 

 @FreeBornAngel 👍 Please keep me updated on this.—

**Comment by alexk111** [comment]
When you buy something thru BitPay, it normally asks you to enter email and select a currency you want to pay with: BTC or BCH, before showing the payment link. Did it ask you to do that, or it just asked for email and nothing else?
DeBitpay shows the picked currency (BTC/BCH) in a first field of the form with the transaction details. It seems that it's still not clear enough, if such things happen . Any ideas on how it could be clearer?

**Comment by FreeBornAngel** [comment]
Yes, I choose bch on bitpay, but missed your box.Give me a few hours and I will look at it again.


Sent from Yahoo Mail on Android 
 
  On Sun, Oct 21, 2018 at 8:49 AM, Alex Kaul<notifications@github.com> wrote:   
When you buy something thru BitPay, it normally asks you to enter email and select a currency you want to pay with: BTC or BCH, before showing the payment link. Did it ask you to do that, or it just asked for email and nothing else?
DeBitpay shows the picked currency (BTC/BCH) in a first field of the form with the transaction details. It seems that it's still not clear enough, if such things happen . Any ideas on how it could be clearer?

**Comment by FreeBornAngel** [comment]
Sorry, spaced it off.
I saw bch at the top of this instance, I'm gonna assume the other had it, too.
Something is up with bitpay, they said they saw the last transaction, but haven't refunded it.
They say I sent it to a btc address, but I wouldn't know the difference.

**Comment by alexk111** [comment]
I've just checked the bch explorer link you sent in the first comment, and don't understand why they tell that you sent btc and don't make a refund. You definitely made the transfer in bch, Then 13 hours later bitpay moved the funds somewhere (probably their cold storage).

Show them your original txid: https://explorer.bitcoin.com/bch/tx/872d6e20d1070e763a906d989f8e778878986bf83be0501fe121db93c9fdba96
It clearly states that the bch transfer was made FROM BCH address TO BCH address.

And the following transaction shows that they can move your funds without problems:
https://explorer.bitcoin.com/bch/tx/168b98fa2fe4ca07c0c18fd1dc24c0162055787e7581c4bc0e4471dd6f17e6df

**Comment by FreeBornAngel** [comment]
They refunded it today, but I still can't get my wallet to work.They say it's just me complaining, so they think my device is compromised.Just my luck.They said your transactions may or may not credit to my card and told me it violates their terms so quit that.I'm sure it's kyc related.

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 26, 2018 at 8:11 PM, Alex Kaul<notifications@github.com> wrote:   
I've just checked the bch explorer link you sent in the first comment, and don't understand why they tell that you sent btc and don't make a refund. You definitely made the transfer in bch, Then 13 hours later bitpay moved the funds somewhere (probably their cold storage).

Show them your original txid: https://explorer.bitcoin.com/bch/tx/872d6e20d1070e763a906d989f8e778878986bf83be0501fe121db93c9fdba96
It clearly states that the bch transfer was made FROM BCH address TO BCH address.

And the following transaction shows that they can move your funds without problems:
https://explorer.bitcoin.com/bch/tx/168b98fa2fe4ca07c0c18fd1dc24c0162055787e7581c4bc0e4471dd6f17e6df

**Comment by alexk111** [comment]
One more question. Was the payment made to pay for something via bitpay, or to load funds on your bitpay card?

**Comment by FreeBornAngel** [comment]
Load the card.
It's definitely this device, I got on a new one and the wallet worked fine.android 4.4.2 doesnt with the Bitcoin.com wallet.

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 29, 2018 at 1:13 AM, Alex Kaul<notifications@github.com> wrote:   
One more question. Was the payment made to pay for something via bitpay, or to load funds on your bitpay card?

**Comment by alexk111** [comment]
So you made another transfer on a different device and it worked without problems? All the same steps: got bitpay link, decoded with debitpay, sent bch to the decoded address, right?

**Comment by FreeBornAngel** [comment]
No, not debitpay.

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 30, 2018 at 5:15 AM, Alex Kaul<notifications@github.com> wrote:   
So you made another transfer on a different device and it worked without problems? All the same steps: got bitpay link, decoded with debitpay, sent bch to the decoded address, right?

**Comment by alexk111** [comment]
Thanks for all the provided details. If the problem persists, then probably Bitpay card loading process works differently from buying via Bitpay.

If anyone else has this problem please reopen the issue.
